name: sleek_circular_slider
description: Customizable Circular Slider & Progress
version: 1.3.0-nullsafe
homepage: https://github.com/kthecoder/sleek_circular_slider

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
